run:
  timeout: 5m
  tests: true

output:
  formats:
    - name: colored-line-number
      color: true
      line-number: true

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gofmt
    - goimports
    - misspell

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
